# Generated by Django 6.0.4 on 2026-04-29 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_until',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
