# Generated by Django 6.0.4 on 2026-04-29 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_discount_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_until',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
