# Generated by Django 6.0.4 on 2026-04-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tasks', '0002_task_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
