# Generated by Django 6.0.4 on 2026-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='firma',
            field=models.CharField(default='Firma', max_length=100, verbose_name='Firma'),
        ),
    ]
